# Generated by Django 3.2 on 2022-01-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='shots',
            field=models.ImageField(null=True, upload_to='movie_shots/<django.db.models.fields.CharField>', verbose_name='Кадры из фильма'),
        ),
        migrations.DeleteModel(
            name='MovieShots',
        ),
    ]
