# Generated by Django 3.2 on 2022-01-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20220117_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieshots',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
