# Generated by Django 3.2 on 2022-01-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_movieshots_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshots',
            name='title',
        ),
    ]
