# Generated by Django 3.2 on 2022-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20220118_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshots',
            name='image',
            field=models.ImageField(upload_to='serial_shots/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=models.ImageField(upload_to='serials/<django.db.models.fields.CharField>', verbose_name='Постер'),
        ),
    ]
