# Generated by Django 3.2 on 2022-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20220119_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=models.ImageField(upload_to='serials/', verbose_name='Постер'),
        ),
    ]
