# Generated by Django 3.2 on 2022-01-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_delete_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.CharField(max_length=160, null=True, verbose_name='URL'),
        ),
    ]
