# Generated by Django 3.2 on 2022-01-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_actor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='url',
            field=models.CharField(max_length=160, null=True, unique=True, verbose_name='URL'),
        ),
    ]
