# Generated by Django 3.2 on 2022-01-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_alter_actor_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='url',
            new_name='slug',
        ),
    ]
